version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::479470245610:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-G9548FSTAG70"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1F290MH2TFDKF"
cloudformation_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1WBK8TJ2ZOG7L"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-18vzd1ltl0hs"
image_repository = ""
region = "eu-central-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-AZY4ZL5LD6F5"
cloudformation_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-NW3105V7XOP3"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-6m3g0gvwkin8"
image_repository = ""
region = "eu-central-1"
