version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::479470245610:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-TUV608L56HD9"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-SAO9FOIQOIBC"
cloudformation_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-D311B2KSKR9J"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-hwfonrua1yhy"
image_repository = "479470245610.dkr.ecr.eu-central-1.amazonaws.com/ge-dev-repo"
region = "eu-central-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1EKRNX4XPNWQT"
cloudformation_execution_role = "arn:aws:iam::479470245610:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1FNVQFSRWMBTY"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-15tzt1cy0shsp"
image_repository = "479470245610.dkr.ecr.eu-central-1.amazonaws.com/ge-prod-repo"
region = "eu-central-1"
